# Generated by Django 6.0.5 on 2026-05-18 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_suscriptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PostImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='posts/galeria/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, help_text='Texto descriptivo para accesibilidad', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='blog.post')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Imágenes de Galería',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
